use dataproject;

-- DROP TABLE O_Items;
-- DROP TABLE orders;
-- DROP TABLE users;
-- DROP TABLE items;
-- DROP TABLE restaurant;
-- DROP TABLE driver;

create table Users(
ID INT(6) NOT NULL,
Fname VARCHAR(50) NOT NULL,
Lname VARCHAR(50),
UserName VARCHAR(50) NOT NULL,
Upass VARCHAR(50) NOT NULL,
Funds DOUBLE(6, 2) NOT NULL,
Address VARCHAR(100) NOT NULL,
Birthday VARCHAR(10),
Email VARCHAR(100) NOT NULL,
PRIMARY KEY (ID)
);

CREATE TABLE Restaurant(
ID INT(6) NOT NULL,
Rname VARCHAR(50) NOT NULL,
Address VARCHAR(100) NOT NULL,
PRIMARY KEY (ID)
);

CREATE TABLE Driver(
ID INT(6) NOT NULL,
Fname VARCHAR(50) NOT NULL,
Lname VARCHAR(50) NOT NULL,
CarModel VARCHAR(75) NOT NULL,
Plate VARCHAR(6) NOT NULL,
Insurance VARCHAR(17) NOT NULL,
UserName VARCHAR(50) NOT NULL,
Dpass VARCHAR(50) NOT NULL,
PRIMARY KEY (ID)
);

CREATE TABLE Orders(
ID INT(10) NOT NULL,
TotalPrice Double(6,2) NOT NULL,
RID INT(6) NOT NULL,
DID INT(6) NOT NULL,
UID INT(6) NOT NULL,
PRIMARY KEY (ID),
FOREIGN KEY (DID) REFERENCES Driver(ID),
FOREIGN KEY (UID) REFERENCES Users(ID),
FOREIGN KEY (RID) REFERENCES Restaurant(ID)
);

CREATE TABLE Items(
ID INT(16) NOT NULL,
RID INT(6) NOT NULL,
Iname VARCHAR(50) NOT NULL,
Price DOUBLE(4,2) NOT NULL,
Decript VARCHAR(1000),
PRIMARY KEY (ID),
FOREIGN KEY (RID) REFERENCES Restaurant(ID)
);

CREATE TABLE O_Items(
O_ID INT (10) NOT NULL,
Item_ID INT(16) NOT NULL,
Quant INT(2) NOT NULL,
Comments VARCHAR(1000),
CONSTRAINT PK_O_Items PRIMARY KEY(O_ID, Item_ID),
FOREIGN KEY (O_ID) REFERENCES Orders(ID),
FOREIGN KEY (Item_ID) REFERENCES Items(ID)
);